### ISSUE TITLE
Generate functioning component

### ISSUE THREAD

**Issue by destructobeam** [eventide-project/command-line-component-generator#7] opened 2018-11-29 08:02 UTC
Sorry if this has been addressed already, I checked commits and updated latest gem and couldn’t see any mention.

Would be helpful if this utility generated a fully functioning component, at the moment nothing is placed in `lib/component_name/messages/{commands,events}` directories, which is then throwing errors on init.

Having example files here would be cool, or maybe the ability to pass args to the generator for which command/event names the user would like to skeleton?

Thanks!

**Comment by sbellware** [comment] 2018-11-29 17:26
There's no real expectation for the skeleton to be a functioning component. It's just a placeholder for the work that is to come.

Loading a component that doesn't actually do anything wouldn't really have any value. It doesn't change what someone new would learn. It would just start a Ruby process with some files loaded. That doesn't prove anything about the component that was generated.

We won't offer special way to add files and classes to a component. That's already something that everyone's editor can do. And someone who doesn't know what messages, events, and commands are won't be benefited by being able to merely load a component that doesn't have messages defined. The inability to load the newly-generated, incomplete component is in fact a valuable signal to the new developer that they need to stop and get some grasp of what needs to be done next.

I can see the value for "scaffolding" events, commands, handlers, entities, projections, etc, for people who are brand new to the toolkit and the architecture. However, that won't do much good either. Service architecture is so vastly different from something like Rails apps that there's no expectation for code generation and hacking/refactoring to be the predominant developer workflow.

I think the ultimate issue is likely an expectation set by something like Rails, and the presumptions that development workflows in Rails apply to anything other than things like Rails.

Nevertheless, we can't afford to do Railsy things and bring in Railsy habits into the universe of services. And experience has borne out that those kinds of tools are only useful to adopters for a few minutes. And there's ultimately more benefit to addressing knowledge gaps with learning, rather than automation.

There's no way to get from Rails to services by doing Rails things, like scaffolding, hacking, and refactoring. There's no way to have a survivable services project by importing those predispositions into an architecture and environment that is predicated on much more rigor.

That said, it only takes a little bit of non-hacking learning to close the gap between what is known and what is not known. There's a prior need for some basic orientation to service development before jumping in.

Once a developer new to services gets past that hump, they also see the relative futility to the learning process that loading an incomplete component offers. In the end, the component generator isn't really intended as the first stop on the learning adventure. A developer who wants a basic look at a basic component implementation is better served by materials explicitly geared for such, like the examples provided with the toolkit: http://docs.eventide-project.org/examples/at-a-glance.html.

The gap between ORM+MVC web apps is much more vast than can be imagined from the vantage of ORM+MVC web apps. That's why so many services initiatives undertaken by Rails developers end up with the broken hopes and broken dreams of distributed monoliths rather than services.

At this level (if we can call it that) of development and architecture, it's expected that some preliminary learning beyond the scope of editing and running code will happen first. That's not the case for environments like Rails, but it is true - and needs to be true - for environments like service architectures.

In the end, I would not expect someone with absolutely no background in service architecture and development to be able to drop into service code and presume to bring the rapid prototyping ethos that they've been conditioned to by something like Rails.

It's valuable to insert an interrupt in the presumptiveness so that it's made clear that this kind of work is going to require a bit more up-front understanding and knowledge. The inability of a newly-generated component to load _is_ that interrupt.

And while it might be harsh to say, if a newly-generated, incomplete component not loading is the thing that turns a dev away, then that's probably a good thing. Service architecture and development requires a higher level of rigor and investment than rapid prototyping on Rails. A developer who _needs_ the instant gratification of rapid prototyping will likely do more harm than good on a services project. 

On the average team, some developers will be more naturally predisposed to the rigor expectations of services work right off the bat, and some will need more time to naturally and gently make the transition. And that's a good and natural thing. When undertaking a services initiative, an entire team should not be making the transition all at once. Only those who are naturally inclined should lead the charge. A services project would not be survivable by including every developer at every skill level in the early stages of the work.

I'm going to close this issue, but I'm open to keep the conversation going if you like.

**Comment by destructobeam** [comment] 2018-11-29 21:15
Thank you for your considered response. I’m happy with the issue being closed, but would like to respond with a few points, now having better understood some of your intentions.

While I understand your concerns regarding adding a feature that does too much generation in lieu of the developer fully realising key concepts, the conflation of wanting to easily create a minimal code outline, with lack of knowledge, is not always the correct assumption. Generating an outline I can see as being useful throughout a project, where as “adding” files I agree is largely useless. Otherwise why would this utility exist in the first place?

In regards to your wishes for the developer to learn before creating, I would suggest that those two processes often go hand-in-hand; that while learning the concepts, building, breaking, and fixing demo projects would—in many cases—help to solidify the understanding of those concepts, and more importantly the implementation of those concepts.

I would also consider the potential for adoption of this project, including collaboration, and an ecosystem surrounding it. While it seems known to be useful for large, somewhat idempotent applications—as expressed in the example code, there are use cases less rigid that I think would benefit from this architecture. Refactoring and iterating on functionality are important in these smaller cases especially. If this project doesn’t wish to cater to those use cases I understand, but I think that would be a shame as there is a great foundation here.

Overall I think a balance could be struck between ease of use and keeping the fundamentals pure.

**Comment by sbellware** [comment] 2018-11-29 21:58
Yup. I totally agree. 

The problem that we've faced is that we've never seen a balance between ease of use and correctness implemented practically.

The most important thing for me is that we keep the balance between a solid, clean toolkit implementation, and a minimum bar of entry so that adopters don't presume that all web development is as ad hoc as rapid prototyping with ORM+MVC frameworks.

I'm not sure that it can be made so easy as to obviate a bare minimum of study and and learning.

But then, I'm biased to what I've been exposed to, and I accept that my perspective is skewed.

I'm definitely open to suggestions on all fronts. And I will probably push back on anything that over-simplifies.

I'm certainly curious about your perspective of applications that don't require more elaborate considerations like idempotence, concurrency, reservation pattern, etc.

I want to clarify a bit my points on refactoring and things that are otherwise more appropriate to ad hoc rapid prototyping of the Rails ilk... We still do refactoring, of course. But when we ship a component to production, the refactoring ends there. Because of the permanence of message contracts - not just in Eventide, but in any message-based systems environment - it can't be expected that we can ship code based on shallow or incomplete analyses and get away with it. The cost of remediation is way to high to be able to afford doing those kinds of things except when absolutely necessary.

So, I've been on the fence as to whether to make the newly-generated project loadable and runnable. My dialog here with you has made me shift my position, and it has shown that I've allowed myself to violate my own rules and standards for usability.

The newly-generated component raises an error. That is going to cause a new user to experience anxiety, and anxiety is going to have an impact on learning capacity and receptiveness - even if a tiny bit. And that's not fare to inject into anyone's psychology when they're already experiencing the anxiety of the exploration of a new architecture and a new tool.

And there's more to this from the usability angle: People who are already users of Eventide don't use the component generator. So, it may indeed be something that is entirely geared for new users.

I'm going to re-open this issue and make a couple of changes to make it more friendly.

**Comment by sbellware** [comment] 2018-11-29 22:40
I just released a new version of the component generator (v1.0.0.1). The component that it generates will load without failing.

**Closed as completed by sbellware** 2018-11-29 22:40 UTC

**Comment by destructobeam** [comment] 2018-11-30 03:22
Yeah, it is a hard balance to get right, I appreciate that you are accepting of
feedback while keepping the nature of the toolkit in mind.

Sorry, to be more clear, I meant idempotency of code/structure, not data
associated with a service. That's interesting regarding your freeze on production, how do you manage
shifting requirements from your services when they pop up, do you use versioning of your
components to accomplish this?

My use case is that I'm looking at building a logistics platform, initially for
my own use, but expect in future to have client requirements I haven't forseen. Hence I
only see the base architecture remaining fairly static.

The plan is to build a GraphQL API around the services for web applications, using database
views. If I have the wrong idea here, are there any examples or documentation I should be looking at regarding
integration points for building gateway APIs?

Thanks for those changes, will give it a crack.

**Comment by sbellware** [comment] 2018-11-30 04:54
In the case of shifting requirements, the pain can't be mitigated. Either message versioning has to be used (either with up-casting or branching logic), or legacy streams need to be re-written. The solution depends in the particular circumstances. Message metadata has an attribute for a version value if versioning is the right solution.

But it should be said that these things shouldn't be something we volunteer for. Meaning, insufficient analysis shouldn't be the cause of having to create new message versions or new streams. Such a lapse would be infuriating for its cost and because it's otherwise avoidable.

So, requirements _do_ change in the real world. But it's thankfully rare. Or at least, it should be.

The view data stuff you describe sounds about right. Nothing sounds obviously wrong with it.

We don't have any specific documentation or examples for gateway APIs. That stuff is quite separated from services, so however you like doing it now is how you'd continue doing it.

If you're calling APIs as a result of handling messages in services, there are some basic circumstances to be aware of. Specifically that an API can be called, and then an event written that records the calling of the API, and that event write might fail even though the call has been made. That's just the cost of doing business when a handler does something that can't be atomic though. The only thing you can do is record an event both before and after the API call to at least have a record in case something fails.

If you want to talk more specifics, I'd recommend joining the Eventide Slack and bounce around ideas with the people there: https://eventide-project-slack.herokuapp.com/.
